/* atomvar.h - C ABI for atomvar (lock-free atomic variables in shared memory).
 *
 * GENERATED by `cargo run -p atomvar-ffi --bin atomvar-gen-header`; do not edit.
 *
 * Guarantees: value operations are atomic and lock-free (no fallback locks),
 * not wait-free or single-instruction. Registry operations (open/create by name)
 * take an OS lock. Supported: Linux x86_64 with CMPXCHG16B. Processes must be
 * started fresh (spawn / fork+exec); a plain fork() child gets
 * ATOMVAR_E_FORKED_PROCESS from registry calls.
 *
 * All out-pointers must be non-NULL. Link with -latomvar.
 */
#ifndef ATOMVAR_H
#define ATOMVAR_H

#include <stdbool.h>
#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

typedef enum atomvar_status {
    ATOMVAR_OK = 0,
    ATOMVAR_E_INVALID_ARGUMENT = 1,
    ATOMVAR_E_INVALID_ORDERING = 2,
    ATOMVAR_E_INVALID_NAME = 3,
    ATOMVAR_E_NOT_FOUND = 4,
    ATOMVAR_E_TYPE_MISMATCH = 5,
    ATOMVAR_E_ARENA_FULL = 6,
    ATOMVAR_E_LAYOUT_MISMATCH = 7,
    ATOMVAR_E_FORKED_PROCESS = 8,
    ATOMVAR_E_UNSUPPORTED_CPU = 9,
    ATOMVAR_E_IO = 10,
    ATOMVAR_E_INTERNAL = 11
} atomvar_status;

typedef enum atomvar_ordering {
    ATOMVAR_RELAXED = 0,
    ATOMVAR_ACQUIRE = 1,
    ATOMVAR_RELEASE = 2,
    ATOMVAR_ACQ_REL = 3,
    ATOMVAR_SEQ_CST = 4
} atomvar_ordering;

typedef struct atomvar_uint128 {
    uint64_t lo;
    uint64_t hi;
} atomvar_uint128;

typedef struct atomvar_arena atomvar_arena;
typedef struct atomvar_i64 atomvar_i64;
typedef struct atomvar_u64 atomvar_u64;
typedef struct atomvar_bool atomvar_bool;
typedef struct atomvar_f64 atomvar_f64;
typedef struct atomvar_u128 atomvar_u128;

/* Best-effort CPU diagnostic: NOT a guarantee (see README, u128 contract). */
int atomvar_init(void);

/* Message for the last failure on this thread; valid until the next failing call. */
const char *atomvar_last_error(void);

/* Opens or creates the named shared-memory arena. capacity 0 adopts an existing
   arena's capacity (or creates one with the default); otherwise it must match. */
int atomvar_arena_open(const char *name, uint32_t capacity, atomvar_arena **out);
void atomvar_arena_close(atomvar_arena *arena);
uint32_t atomvar_arena_capacity(const atomvar_arena *arena);

/* ---------------- i64 ---------------- */
int atomvar_i64_new(int64_t init, atomvar_i64 **out);
/* Opens or creates; init is used only when this call creates the variable. */
int atomvar_arena_i64(const atomvar_arena *arena, const char *name, int64_t init, atomvar_i64 **out);
/* Opens an existing variable (ATOMVAR_E_NOT_FOUND otherwise). */
int atomvar_arena_open_i64(const atomvar_arena *arena, const char *name, atomvar_i64 **out);
void atomvar_i64_free(atomvar_i64 *h);
int atomvar_i64_load(const atomvar_i64 *h, int order, int64_t *out);
int atomvar_i64_store(const atomvar_i64 *h, int64_t value, int order);
int atomvar_i64_swap(const atomvar_i64 *h, int64_t value, int order, int64_t *old);
/* Strong CAS. *previous receives the value seen; *exchanged tells whether it was replaced. */
int atomvar_i64_compare_exchange(const atomvar_i64 *h, int64_t expected, int64_t desired, int success, int failure, int64_t *previous, bool *exchanged);

/* Weak CAS: may fail spuriously; use inside a retry loop. */
int atomvar_i64_compare_exchange_weak(const atomvar_i64 *h, int64_t expected, int64_t desired, int success, int failure, int64_t *previous, bool *exchanged);

/* fetch_*: *out = value before the op. *_and_get: *out = value after the op. */
int atomvar_i64_fetch_add(const atomvar_i64 *h, int64_t value, int order, int64_t *out);
int atomvar_i64_fetch_sub(const atomvar_i64 *h, int64_t value, int order, int64_t *out);
int atomvar_i64_fetch_and(const atomvar_i64 *h, int64_t value, int order, int64_t *out);
int atomvar_i64_fetch_or(const atomvar_i64 *h, int64_t value, int order, int64_t *out);
int atomvar_i64_fetch_xor(const atomvar_i64 *h, int64_t value, int order, int64_t *out);
int atomvar_i64_fetch_max(const atomvar_i64 *h, int64_t value, int order, int64_t *out);
int atomvar_i64_fetch_min(const atomvar_i64 *h, int64_t value, int order, int64_t *out);
int atomvar_i64_add_and_get(const atomvar_i64 *h, int64_t value, int order, int64_t *out);
int atomvar_i64_sub_and_get(const atomvar_i64 *h, int64_t value, int order, int64_t *out);

/* ---------------- u64 ---------------- */
int atomvar_u64_new(uint64_t init, atomvar_u64 **out);
/* Opens or creates; init is used only when this call creates the variable. */
int atomvar_arena_u64(const atomvar_arena *arena, const char *name, uint64_t init, atomvar_u64 **out);
/* Opens an existing variable (ATOMVAR_E_NOT_FOUND otherwise). */
int atomvar_arena_open_u64(const atomvar_arena *arena, const char *name, atomvar_u64 **out);
void atomvar_u64_free(atomvar_u64 *h);
int atomvar_u64_load(const atomvar_u64 *h, int order, uint64_t *out);
int atomvar_u64_store(const atomvar_u64 *h, uint64_t value, int order);
int atomvar_u64_swap(const atomvar_u64 *h, uint64_t value, int order, uint64_t *old);
/* Strong CAS. *previous receives the value seen; *exchanged tells whether it was replaced. */
int atomvar_u64_compare_exchange(const atomvar_u64 *h, uint64_t expected, uint64_t desired, int success, int failure, uint64_t *previous, bool *exchanged);

/* Weak CAS: may fail spuriously; use inside a retry loop. */
int atomvar_u64_compare_exchange_weak(const atomvar_u64 *h, uint64_t expected, uint64_t desired, int success, int failure, uint64_t *previous, bool *exchanged);

/* fetch_*: *out = value before the op. *_and_get: *out = value after the op. */
int atomvar_u64_fetch_add(const atomvar_u64 *h, uint64_t value, int order, uint64_t *out);
int atomvar_u64_fetch_sub(const atomvar_u64 *h, uint64_t value, int order, uint64_t *out);
int atomvar_u64_fetch_and(const atomvar_u64 *h, uint64_t value, int order, uint64_t *out);
int atomvar_u64_fetch_or(const atomvar_u64 *h, uint64_t value, int order, uint64_t *out);
int atomvar_u64_fetch_xor(const atomvar_u64 *h, uint64_t value, int order, uint64_t *out);
int atomvar_u64_fetch_max(const atomvar_u64 *h, uint64_t value, int order, uint64_t *out);
int atomvar_u64_fetch_min(const atomvar_u64 *h, uint64_t value, int order, uint64_t *out);
int atomvar_u64_add_and_get(const atomvar_u64 *h, uint64_t value, int order, uint64_t *out);
int atomvar_u64_sub_and_get(const atomvar_u64 *h, uint64_t value, int order, uint64_t *out);

/* ---------------- bool ---------------- */
int atomvar_bool_new(bool init, atomvar_bool **out);
/* Opens or creates; init is used only when this call creates the variable. */
int atomvar_arena_bool(const atomvar_arena *arena, const char *name, bool init, atomvar_bool **out);
/* Opens an existing variable (ATOMVAR_E_NOT_FOUND otherwise). */
int atomvar_arena_open_bool(const atomvar_arena *arena, const char *name, atomvar_bool **out);
void atomvar_bool_free(atomvar_bool *h);
int atomvar_bool_load(const atomvar_bool *h, int order, bool *out);
int atomvar_bool_store(const atomvar_bool *h, bool value, int order);
int atomvar_bool_swap(const atomvar_bool *h, bool value, int order, bool *old);
/* Strong CAS. *previous receives the value seen; *exchanged tells whether it was replaced. */
int atomvar_bool_compare_exchange(const atomvar_bool *h, bool expected, bool desired, int success, int failure, bool *previous, bool *exchanged);

/* Weak CAS: may fail spuriously; use inside a retry loop. */
int atomvar_bool_compare_exchange_weak(const atomvar_bool *h, bool expected, bool desired, int success, int failure, bool *previous, bool *exchanged);

/* fetch_*: *out = value before the op. *_and_get: *out = value after the op. */
int atomvar_bool_fetch_and(const atomvar_bool *h, bool value, int order, bool *out);
int atomvar_bool_fetch_or(const atomvar_bool *h, bool value, int order, bool *out);
int atomvar_bool_fetch_xor(const atomvar_bool *h, bool value, int order, bool *out);
int atomvar_bool_fetch_nand(const atomvar_bool *h, bool value, int order, bool *out);

/* ---------------- f64 ---------------- */
int atomvar_f64_new(double init, atomvar_f64 **out);
/* Opens or creates; init is used only when this call creates the variable. */
int atomvar_arena_f64(const atomvar_arena *arena, const char *name, double init, atomvar_f64 **out);
/* Opens an existing variable (ATOMVAR_E_NOT_FOUND otherwise). */
int atomvar_arena_open_f64(const atomvar_arena *arena, const char *name, atomvar_f64 **out);
void atomvar_f64_free(atomvar_f64 *h);
int atomvar_f64_load(const atomvar_f64 *h, int order, double *out);
int atomvar_f64_store(const atomvar_f64 *h, double value, int order);
int atomvar_f64_swap(const atomvar_f64 *h, double value, int order, double *old);
/* Strong CAS. *previous receives the value seen; *exchanged tells whether it was replaced. */
int atomvar_f64_compare_exchange(const atomvar_f64 *h, double expected, double desired, int success, int failure, double *previous, bool *exchanged);

/* fetch_*: *out = value before the op. *_and_get: *out = value after the op. */
int atomvar_f64_fetch_add(const atomvar_f64 *h, double value, int order, double *out);
int atomvar_f64_fetch_sub(const atomvar_f64 *h, double value, int order, double *out);
int atomvar_f64_add_and_get(const atomvar_f64 *h, double value, int order, double *out);

/* Exact IEEE-754 bit patterns; compare_exchange on doubles is also bitwise. */
int atomvar_f64_load_bits(const atomvar_f64 *h, int order, uint64_t *out);
int atomvar_f64_store_bits(const atomvar_f64 *h, uint64_t bits, int order);
int atomvar_f64_compare_exchange_bits(const atomvar_f64 *h, uint64_t expected, uint64_t desired, int success, int failure, uint64_t *previous, bool *exchanged);

/* ---------------- u128 ---------------- */
int atomvar_u128_new(atomvar_uint128 init, atomvar_u128 **out);
/* Opens or creates; init is used only when this call creates the variable. */
int atomvar_arena_u128(const atomvar_arena *arena, const char *name, atomvar_uint128 init, atomvar_u128 **out);
/* Opens an existing variable (ATOMVAR_E_NOT_FOUND otherwise). */
int atomvar_arena_open_u128(const atomvar_arena *arena, const char *name, atomvar_u128 **out);
void atomvar_u128_free(atomvar_u128 *h);
int atomvar_u128_load(const atomvar_u128 *h, int order, atomvar_uint128 *out);
int atomvar_u128_store(const atomvar_u128 *h, atomvar_uint128 value, int order);
int atomvar_u128_swap(const atomvar_u128 *h, atomvar_uint128 value, int order, atomvar_uint128 *old);
/* Strong CAS. *previous receives the value seen; *exchanged tells whether it was replaced. */
int atomvar_u128_compare_exchange(const atomvar_u128 *h, atomvar_uint128 expected, atomvar_uint128 desired, int success, int failure, atomvar_uint128 *previous, bool *exchanged);

/* Weak CAS: may fail spuriously; use inside a retry loop. */
int atomvar_u128_compare_exchange_weak(const atomvar_u128 *h, atomvar_uint128 expected, atomvar_uint128 desired, int success, int failure, atomvar_uint128 *previous, bool *exchanged);

#ifdef __cplusplus
}
#endif

#endif /* ATOMVAR_H */
