from typing import Optional

DEFAULT_CAPACITY: int

class Ordering:
    RELAXED: "Ordering"
    ACQUIRE: "Ordering"
    RELEASE: "Ordering"
    ACQ_REL: "Ordering"
    SEQ_CST: "Ordering"

class AtomvarError(Exception): ...
class InvalidOrderingError(AtomvarError): ...
class InvalidNameError(AtomvarError): ...
class ArenaFullError(AtomvarError): ...
class TypeMismatchError(AtomvarError): ...
class NotFoundError(AtomvarError): ...
class LayoutMismatchError(AtomvarError): ...
class ForkedProcessError(AtomvarError): ...
class UnsupportedCpuError(AtomvarError): ...

class _IntBase:
    @property
    def value(self) -> int: ...
    def get(self, order: Ordering = ...) -> int: ...
    def load(self, order: Ordering = ...) -> int: ...
    def set(self, value: int, order: Ordering = ...) -> None: ...
    def store(self, value: int, order: Ordering = ...) -> None: ...
    def get_and_set(self, value: int, order: Ordering = ...) -> int: ...
    def swap(self, value: int, order: Ordering = ...) -> int: ...
    def compare_and_set(self, expect: int, update: int) -> bool: ...
    def compare_exchange(
        self, expected: int, desired: int, success: Ordering = ..., failure: Optional[Ordering] = ...
    ) -> tuple[bool, int]: ...
    def compare_exchange_weak(
        self, expected: int, desired: int, success: Ordering = ..., failure: Optional[Ordering] = ...
    ) -> tuple[bool, int]: ...
    def fetch_add(self, value: int, order: Ordering = ...) -> int: ...
    def fetch_sub(self, value: int, order: Ordering = ...) -> int: ...
    def fetch_and(self, value: int, order: Ordering = ...) -> int: ...
    def fetch_or(self, value: int, order: Ordering = ...) -> int: ...
    def fetch_xor(self, value: int, order: Ordering = ...) -> int: ...
    def fetch_max(self, value: int, order: Ordering = ...) -> int: ...
    def fetch_min(self, value: int, order: Ordering = ...) -> int: ...
    def get_and_add(self, value: int, order: Ordering = ...) -> int: ...
    def add_and_get(self, value: int, order: Ordering = ...) -> int: ...
    def sub_and_get(self, value: int, order: Ordering = ...) -> int: ...
    def increment_and_get(self, order: Ordering = ...) -> int: ...
    def decrement_and_get(self, order: Ordering = ...) -> int: ...
    def get_and_increment(self, order: Ordering = ...) -> int: ...
    def get_and_decrement(self, order: Ordering = ...) -> int: ...

class AtomicInt(_IntBase):
    """Atomic signed 64-bit integer; arithmetic wraps on overflow."""
    def __init__(self, value: int = 0) -> None: ...

class AtomicUInt(_IntBase):
    """Atomic unsigned 64-bit integer; arithmetic wraps on overflow."""
    def __init__(self, value: int = 0) -> None: ...

class AtomicBool:
    def __init__(self, value: bool = False) -> None: ...
    @property
    def value(self) -> bool: ...
    def get(self, order: Ordering = ...) -> bool: ...
    def load(self, order: Ordering = ...) -> bool: ...
    def set(self, value: bool, order: Ordering = ...) -> None: ...
    def store(self, value: bool, order: Ordering = ...) -> None: ...
    def get_and_set(self, value: bool, order: Ordering = ...) -> bool: ...
    def swap(self, value: bool, order: Ordering = ...) -> bool: ...
    def compare_and_set(self, expect: bool, update: bool) -> bool: ...
    def compare_exchange(
        self, expected: bool, desired: bool, success: Ordering = ..., failure: Optional[Ordering] = ...
    ) -> tuple[bool, bool]: ...
    def compare_exchange_weak(
        self, expected: bool, desired: bool, success: Ordering = ..., failure: Optional[Ordering] = ...
    ) -> tuple[bool, bool]: ...
    def fetch_and(self, value: bool, order: Ordering = ...) -> bool: ...
    def fetch_or(self, value: bool, order: Ordering = ...) -> bool: ...
    def fetch_xor(self, value: bool, order: Ordering = ...) -> bool: ...
    def fetch_nand(self, value: bool, order: Ordering = ...) -> bool: ...
    def __bool__(self) -> bool: ...

class AtomicFloat:
    """Atomic f64. CAS compares exact bits (0.0 != -0.0; NaN matches only itself bitwise)."""
    def __init__(self, value: float = 0.0) -> None: ...
    @property
    def value(self) -> float: ...
    def get(self, order: Ordering = ...) -> float: ...
    def load(self, order: Ordering = ...) -> float: ...
    def set(self, value: float, order: Ordering = ...) -> None: ...
    def store(self, value: float, order: Ordering = ...) -> None: ...
    def get_bits(self, order: Ordering = ...) -> int: ...
    def set_bits(self, bits: int, order: Ordering = ...) -> None: ...
    def get_and_set(self, value: float, order: Ordering = ...) -> float: ...
    def swap(self, value: float, order: Ordering = ...) -> float: ...
    def compare_and_set(self, expect: float, update: float) -> bool: ...
    def compare_and_set_bits(self, expect: int, update: int) -> bool: ...
    def compare_exchange(
        self, expected: float, desired: float, success: Ordering = ..., failure: Optional[Ordering] = ...
    ) -> tuple[bool, float]: ...
    def fetch_add(self, value: float, order: Ordering = ...) -> float: ...
    def fetch_sub(self, value: float, order: Ordering = ...) -> float: ...
    def add_and_get(self, value: float, order: Ordering = ...) -> float: ...
    def __float__(self) -> float: ...

class AtomicU128:
    """Atomic unsigned 128-bit integer (CMPXCHG16B)."""
    def __init__(self, value: int = 0) -> None: ...
    @property
    def value(self) -> int: ...
    def get(self, order: Ordering = ...) -> int: ...
    def load(self, order: Ordering = ...) -> int: ...
    def set(self, value: int, order: Ordering = ...) -> None: ...
    def store(self, value: int, order: Ordering = ...) -> None: ...
    def get_and_set(self, value: int, order: Ordering = ...) -> int: ...
    def swap(self, value: int, order: Ordering = ...) -> int: ...
    def compare_and_set(self, expect: int, update: int) -> bool: ...
    def compare_exchange(
        self, expected: int, desired: int, success: Ordering = ..., failure: Optional[Ordering] = ...
    ) -> tuple[bool, int]: ...
    def compare_exchange_weak(
        self, expected: int, desired: int, success: Ordering = ..., failure: Optional[Ordering] = ...
    ) -> tuple[bool, int]: ...

class Arena:
    """Named shared-memory arena; the same name in any process is the same arena."""
    def __init__(self, name: str, capacity: Optional[int] = None) -> None: ...
    @property
    def name(self) -> str: ...
    @property
    def capacity(self) -> int: ...
    def int(self, name: str, init: int = 0) -> AtomicInt: ...
    def uint(self, name: str, init: int = 0) -> AtomicUInt: ...
    def bool(self, name: str, init: bool = False) -> AtomicBool: ...
    def float(self, name: str, init: float = 0.0) -> AtomicFloat: ...
    def u128(self, name: str, init: int = 0) -> AtomicU128: ...
    def open_int(self, name: str) -> AtomicInt: ...
    def open_uint(self, name: str) -> AtomicUInt: ...
    def open_bool(self, name: str) -> AtomicBool: ...
    def open_float(self, name: str) -> AtomicFloat: ...
    def open_u128(self, name: str) -> AtomicU128: ...
    def lookup(self, name: str) -> Optional[str]: ...
    def list(self) -> list[tuple[str, str]]: ...
    def __len__(self) -> int: ...

def cpu_supported() -> bool: ...
